[package]
name = "cc-sandler-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.54", features = ["derive"] }
itertools = "0.14.0"
regex = "1.12.2"
strum = "0.27.2"
strum_macros = "0.27.2"
thiserror = "2.0.17"
